# Generated by Django 4.2.6 on 2023-10-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0002_rename_entity_entidad_adminentidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name_plural': 'Entidades'},
        ),
    ]
