# Generated by Django 4.2.6 on 2023-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0003_alter_entidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
