# Generated by Django 4.2.13 on 2024-06-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0004_alter_comunicado_detalle_alter_comunicado_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(max_length=200, verbose_name='NombreP')),
                ('estudiante', models.CharField(max_length=200, verbose_name='Estudiante')),
                ('tema', models.CharField(max_length=200, verbose_name='Tema')),
                ('profesor', models.CharField(max_length=200, verbose_name='Profesor')),
            ],
        ),
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='comunicados/static/logos'),
        ),
    ]
