# Generated by Django 4.2.13 on 2024-06-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0005_proyectos_alter_entidad_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(max_length=200, verbose_name='NombreP')),
                ('estudiante', models.CharField(max_length=200, verbose_name='Estudiante')),
                ('tema', models.CharField(max_length=200, verbose_name='Tema')),
                ('profesor', models.CharField(max_length=200, verbose_name='Profesor')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminentidad',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='adminentidad',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='publicado_por',
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
        migrations.DeleteModel(
            name='AdminEntidad',
        ),
        migrations.DeleteModel(
            name='Comunicado',
        ),
        migrations.DeleteModel(
            name='Entidad',
        ),
    ]
