# Generated by Django 4.2.13 on 2024-06-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0007_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='profesor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profesor'),
        ),
    ]
