# Generated by Django 4.2.13 on 2024-06-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0008_tema_delete_docente_alter_proyecto_profesor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={},
        ),
    ]
